language: node_js
node_js:
  - "16"
install:
  # Install deps
  - npm install
before_script:
  # Want to be sure that the ecmascript transpiles
  - npm run compile
script:
  # Check style and then run tests
  - npm run lint
  - npm test
